// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0UalrhIiuudWD0pBXF6FF1NjcZAbFGrU',
    appId: '1:883017307577:web:ce2a74bd667f35623b9268',
    messagingSenderId: '883017307577',
    projectId: 'todo-5a2ff',
    authDomain: 'todo-5a2ff.firebaseapp.com',
    storageBucket: 'todo-5a2ff.firebasestorage.app',
    measurementId: 'G-EPH9XY8MMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQy8dbhALuQhDw9VI3nYhufdhTnqCV3w',
    appId: '1:883017307577:android:b5cf2de2a37c589d3b9268',
    messagingSenderId: '883017307577',
    projectId: 'todo-5a2ff',
    storageBucket: 'todo-5a2ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf8ruBlOqqR6xwsqtaYhdeI1SbepFE6UE',
    appId: '1:883017307577:ios:2f45a89f93c6173c3b9268',
    messagingSenderId: '883017307577',
    projectId: 'todo-5a2ff',
    storageBucket: 'todo-5a2ff.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf8ruBlOqqR6xwsqtaYhdeI1SbepFE6UE',
    appId: '1:883017307577:ios:2f45a89f93c6173c3b9268',
    messagingSenderId: '883017307577',
    projectId: 'todo-5a2ff',
    storageBucket: 'todo-5a2ff.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0UalrhIiuudWD0pBXF6FF1NjcZAbFGrU',
    appId: '1:883017307577:web:41d3212e69e5fd523b9268',
    messagingSenderId: '883017307577',
    projectId: 'todo-5a2ff',
    authDomain: 'todo-5a2ff.firebaseapp.com',
    storageBucket: 'todo-5a2ff.firebasestorage.app',
    measurementId: 'G-QMP26ZPKFB',
  );
}
